name: Build and upload conda packages

on:
  release:
    types: [released]

jobs:
  conda_deployment:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.9'
          environment-file: .conda/build_env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          python-version: '3.9'
          user: seanbryan
          label: master
          token: ${{ secrets.ANACONDA_TOKEN }}